# Generated by Django 6.1.1 on 2026-09-11 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, help_text='Usado para firmar (HMAC-SHA256) cada webhook enviado. Se autogenera si se deja vacio.', max_length=100)),
                ('eventos', models.CharField(help_text='Lista separada por comas, p.ej. "servicio.entregado,servicio.novedad".', max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('actua_como', models.ForeignKey(help_text='Usuario ALISTADOR en cuyo nombre actua esta llave para efectos de permisos.', limit_choices_to={'rol': 'ALISTADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='integrations.webhookendpoint')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
