import { addIcons } from 'ionicons';
import {
  logOutOutline,
  addOutline,
  createOutline,
  trashOutline,
  arrowBackOutline,
  sendOutline,
  cameraOutline,
  checkmarkCircleOutline,
  alertCircleOutline,
  cubeOutline,
  bicycleOutline,
  personOutline,
  listOutline,
  homeOutline,
  mapOutline,
  chatbubbleOutline,
  calendarOutline,
  refreshOutline,
  storefrontOutline,
  navigateOutline,
  closeOutline,
  reloadOutline,
  checkmarkOutline,
  informationCircleOutline,
  locationOutline,
  pencilOutline,
  pauseOutline,
  playOutline,
  chevronUpOutline,
  timeOutline,
  keyOutline,
  gitNetworkOutline,
} from 'ionicons/icons';

export function registerIcons(): void {
  addIcons({
    'log-out-outline': logOutOutline,
    'add-outline': addOutline,
    'create-outline': createOutline,
    'trash-outline': trashOutline,
    'arrow-back-outline': arrowBackOutline,
    'send-outline': sendOutline,
    'camera-outline': cameraOutline,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'alert-circle-outline': alertCircleOutline,
    'cube-outline': cubeOutline,
    'bicycle-outline': bicycleOutline,
    'person-outline': personOutline,
    'list-outline': listOutline,
    'home-outline': homeOutline,
    'map-outline': mapOutline,
    'chatbubble-outline': chatbubbleOutline,
    'calendar-outline': calendarOutline,
    'refresh-outline': refreshOutline,
    'storefront-outline': storefrontOutline,
    'navigate-outline': navigateOutline,
    'close-outline': closeOutline,
    'reload-outline': reloadOutline,
    'checkmark-outline': checkmarkOutline,
    'information-circle-outline': informationCircleOutline,
    'location-outline': locationOutline,
    'pencil-outline': pencilOutline,
    'pause-outline': pauseOutline,
    'play-outline': playOutline,
    'chevron-up-outline': chevronUpOutline,
    'time-outline': timeOutline,
    'key-outline': keyOutline,
    'git-network-outline': gitNetworkOutline,
  });
}
