# Generated by Django 6.1.1 on 2026-09-11 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PLANEADA', 'Planeada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada')], default='PLANEADA', max_length=20)),
                ('motorizado', models.ForeignKey(limit_choices_to={'rol': 'MOTORIZADO'}, on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega'), ('RECOLECCION', 'Recoleccion')], max_length=20)),
                ('zona', models.CharField(max_length=100)),
                ('direccion_origen', models.CharField(blank=True, max_length=255)),
                ('direccion_destino', models.CharField(blank=True, max_length=255)),
                ('fecha_agenda', models.DateField()),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado a ruta'), ('RECIBIDO_CENTRO', 'Recibido en centro'), ('EN_TRANSITO', 'En transito'), ('ENTREGADO', 'Entregado'), ('RECOLECTADO', 'Recolectado'), ('NOVEDAD', 'Con novedad'), ('DEVUELTO', 'Devuelto al centro')], default='CREADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='inventory.producto')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='services.ruta')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('accion', models.CharField(choices=[('DEVOLVER_A_CENTRO', 'Devolver a centro'), ('REINTENTAR', 'Reintentar')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='services.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='services.servicio')),
            ],
            options={
                'ordering': ['enviado_en'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='evidencias/fotos/')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='evidencias/firmas/')),
                ('capturado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='services.servicio')),
            ],
        ),
    ]
