# Generated by Django 6.1.1 on 2026-09-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoGeocodificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direccion_geocodificada', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punto_geocodificado', to='services.servicio')),
            ],
            options={
                'verbose_name': 'Punto geocodificado',
                'verbose_name_plural': 'Puntos geocodificados',
            },
        ),
    ]
