# Generated by Django 6.1.1 on 2026-09-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('centro_mensajeria', models.CharField(max_length=100)),
                ('disponible_chatbot', models.BooleanField(default=False)),
            ],
        ),
    ]
